@startuml MC Protocol device

skinparam backgroundColor #FAFAFA
skinparam classBackgroundColor #EBF3FB
skinparam classBorderColor #2E75B6
skinparam classHeaderBackgroundColor #3e6d99
skinparam classFontColor #FFFFFF
skinparam classAttributeFontColor #1F1F1F
skinparam arrowColor #1F4E79
skinparam packageBackgroundColor #F5F5F5
skinparam packageBorderColor #AAAAAA
skinparam shadowing false

package "vc::device" {

    package "MC Protocol (Mitsubishi PLC)" {

        enum McMsgItfType {
            EthernetTCP
            Serial
        }

        enum McFrameType {
            Frame1E
            Frame3E
            Frame1C
            Frame3C
        }

        enum McDataCode {
            Binary
            Ascii
        }

        class McProtocolDevice {
            .. This device handle IO polling query ..
            + deviceConnect(void) : bool
            + deviceDisconnect(void) : bool
            + isDeviceConnect(void) : bool
            + setDevcieConfig(IDeviceCfg*) : void
            + setMcProtocolConfig(McProtocolConfig&) : void
            + mcProtocolConfig(void) : McProtocolConfig
            + getAvailableBits(void) : QStringList 
            + getAvailableWords(void) : QStringList
            
            - onPollingTimerTimeOut() : void
            - onMsgInterfaceReadReady() : void
            
            - initialize_mc_device() : bool
            - excute_request() : void
            - polling_query() : void
            - request_handle() : void
            - response_handle() : void
            - retry_request_handle() : void
        }

        class McProtocolConfig {
            - m_frame_type : McFrameType
            - m_context : std::shared_ptr<McContext>
            .. this method will configurate for McContext ..
            + configMcProtocol(frame_type : McFrameType) : bool
            + context() : McContext*
        }

        class McContext << abstract >>{
            - m_data_code : McDataCode

            + {abstract} frameType() : McFrameType
            + {abstract} msgInterfaceType() : McMsgItfType
            + dataCode(void) : McDataCode
            + {abstract} clone() : *McContext
            + toJson(void) : QJsonObject
            + fromJson(QJsonObject&) : bool
            + setDeviceMap(McDeviceMap*) : void
            + getDeviceMap(void) : McDeviceMap*
        }

        class Factory {
            .. static method: Context factory use for generate context corresponse to frame type..
            .. when user change setting frame type -> confirm they want to change ..
            + {static} contextFactory(frame_type : McFrameType) : McContext*
        }

        class McContext3E {
            .. 3E Frame context (Ethernet TCP or UDP) ..
            + m_network : quint8
            + m_pc : quint8
            + m_dest_module_io : quint16
            + m_multi_station : quint8
            + m_monitoring_time : quint16 
            + m_sub_header : quint16 {const} = 0x5000
        }
        
        class McContext1E {
            .. 1E Frame context (Ethernet TCP or UDP) ..
            
        }

        class McContext1C {
            .. 1C Frame context (Serial port) ..
            
        }

        class McContext3C {
            .. 3C Frame context (Serial port) ..
        }

        class McFrameAbstract {
            + {abstract} makeSendFrame() : FrameReturnCode
            + {abstract} parseReceiveFrame() : FrameReturnCode
            + {abstract} lastErrorDescription() : QString
        }

        class Frame1E {

        }

        class Frame3E {

        }

        class Frame1C {

        }

        class Frame3C {

        }

        class McMsgInterface {
            + {abstract} setConfig(McMsgItfConfig* cfg) : bool    
            + {abstract} connectionCheck() : void 
            + {abstract} connectToDevice() : bool
            + {abstract} disconnectFromDevice() : bool
            + {abstract} currentState() : MsgItfState
            + {abstract} sendMsg() : MsgItfState
            + {abstract} receiveMsg() : MsgItfState
            + {abstract} type() : McItfType
            + {abstract} clone() : void

            .. Signals ..
            + connectionCheckingFinished(bool) : void
        }

        class McMsgEthernetTCP {
            .. Ethernet TCP/IP message interface ..
        }

        class McMsgSerialPort {
            .. Serial message interface via COM Port ..
        }

        class McMsgItfConfig << abstract >> {
            + setConnectTimeout(void) : bool
            + setWriteTimeout(void) : bool
            + setWaitResponseTimeout(void) : bool
            + toJson(void) : QJsonObject
            + fromJson(QJsonObject &obj) : bool 
        }

        class McMsgEthernetTcpCfg {
            + ip_address : QString
            + port_number : int
        }

        class McMsgSerialCfg {
            + port_name : QString
            + baudrate : int
        }

        class DeviceParse {
            .. Giữ nguyên dạng dữ liệu đọc được ghi vào bytes ..
            .. Khi đọc thì parse ra ..
        }

        note right of McProtocolDevice
            * McProtocolDevice configurate 
                via McProtocolConfig(IDeviceCfg)
            * McMsgInterface and McFrameAbstract 
                will be allocate before connect to device
        end note
    }
}

' Inheritance
IDevice             <|-- McProtocolDevice
IDeviceCfg       <|-- McProtocolConfig

McMsgItfConfig      <|-- McMsgEthernetTcpCfg
McMsgItfConfig      <|-- McMsgSerialCfg

McMsgInterface      <|-- McMsgEthernetTCP
McMsgInterface      <|-- McMsgSerialPort
McContext           <|-- McContext1C
McContext           <|-- McContext1E
McContext           <|-- McContext3C
McContext           <|-- McContext3E

McFrameAbstract     <|-- Frame1E
McFrameAbstract     <|-- Frame3E
McFrameAbstract     <|-- Frame1C
McFrameAbstract     <|-- Frame3C

' Enum usage
McMsgInterface      --> McMsgItfType
' McProtocolDevice    --> McMsgItfType
' McFrameAbstract     --> McDataCode
McProtocolConfig    --> McDataCode
McProtocolConfig    --> McFrameType


' Dependencies
McProtocolConfig    <.. McContext               : protocol context
McProtocolConfig    <.. McMsgItfConfig          : msg interface config
McProtocolDevice    *.. McMsgInterface          : msg interface
McProtocolDevice    *.. McFrameAbstract         : frame maker

@enduml