@startuml MC Device Mutex Sequence

participant "Thread Outside" as outside #LightBlue
participant "Thread MC Device" as MC #LightGreen
participant "Configuration buffer" as config #OrangeRed
participant "Request Queue" as request #LightCoral

== MC Device Handle ==

activate config

MC -> config : Connect
MC -> config : Disconnect

deactivate config

== Thread Outside handle ==

activate request

note right of request: Mutex = LOCKED
outside -> request : push request (outside thread)
note right of request: Mutex = UNLOCKED

note right of request: Mutex = LOCKED
MC -> request : push request (polling query)
note right of request: Mutex = UNLOCKED

deactivate request



' ' Tùy chỉnh màu sắc để dễ phân biệt
' participant "Thread A" as TA #LightBlue
' participant "Thread B" as TB #LightGreen
' participant "SharedBuffer\n(Có chứa Mutex)" as Buffer #LightCoral

' == Bắt đầu luồng xử lý song song ==

' TA -> TA : Tính toán dữ liệu cục bộ\n(Không cần lock)
' TB -> TB : Tính toán dữ liệu cục bộ\n(Không cần lock)

' ' Thread A yêu cầu lấy lock trước
' TA -> Buffer : lock_mutex()
' activate Buffer
' note right of Buffer: Mutex = LOCKED\n(Thread A đang giữ)

' ' Thread B cũng muốn lấy lock nhưng bị chậm hơn
' TB -> Buffer : lock_mutex()
' note right of TB #ffaaaa: THREAD B BỊ BLOCKED!\nPhải chờ đến khi Mutex được nhả.

' ' Khối critical thể hiện Vùng găng (Critical Section)
' critical Vùng Găng (Chỉ 1 Thread được chạy)
'     TA -> Buffer : write_data(data_A)
'     TA -> Buffer : update_counter()
' end

' ' Thread A xong việc, nhả lock
' TA -> Buffer : unlock_mutex()
' ' deactivate Buffer
' note right of Buffer: Mutex = UNLOCKED

' == Ngay lập tức sau khi A nhả lock ==

' ' Lúc này Thread B mới lấy được lock và thoát khỏi trạng thái chờ
' note right of Buffer: Mutex = LOCKED\n(Thread B đã lấy được)
' ' activate Buffer
' TB <-- Buffer : (Tiếp tục thực thi)

' critical Vùng Găng
'     TB -> Buffer : write_data(data_B)
'     TB -> Buffer : update_counter()
' end

' TB -> Buffer : unlock_mutex()
' deactivate Buffer
' note right of Buffer: Mutex = UNLOCKED

@endumls
